### ISSUE TITLE
Documentation of Use Cases 3, 4, 5

### ISSUE THREAD

**Issue by SergioMartinezUCLM** [SergioMartinezUCLM/ISOFT2-2021-A04#9]
This is mainly focused on the flow of events, but verbal descriptions may also be useful.

**Comment by IsmaelCaballero** [comment]
Hi! 
Please, let me two comments:

1. If you upload some files or if you refer to some code is quite useful to include the link to the corresponding resource, so that it would be easier to follow the evolution of your work
2. Please, keep updated the [wiki ](https://github.com/SergioMartinezUCLM/ISOFT2-2021-A04/wiki) section with your advances so that it will be easier to know where exactly you are at a given time.

Good work! 
I wish a nice weekend
Ismael 

)
